### ISSUE TITLE
Crash when pressing "Start" button, provided by vk bots functionality

### ISSUE THREAD

**Issue by zakulqi** [yageorgiy/botman-vk-community-callback-driver#5]
Request string
```
{"type":"message_new","object":{"message":{"date":1600265466,"from_id":11111111,"id":65,"out":0,"peer_id":11111111,"text":"Начать","conversation_message_id":1,"fwd_messages":[],"important":false,"random_id":0,"attachments":[],"payload":"{\"command\":\"start\"}","is_hidden":false},"client_info":{"button_actions":["text","vkpay","open_app","location","open_link"],"keyboard":true,"inline_keyboard":true,"carousel":false,"lang_id":0}},"group_id":11111,"event_id":"82d32482992f91243a","secret":"asdyhauihsdiyasd"}
```

Error str

```local.ERROR: Undefined index: __message {"exception":"[object] (ErrorException(code: 0): Undefined index: __message at vendor\\yageorgiy\\botman-vk-community-callback-driver\\src\\VkCommunityCallbackDriver.php:242)
[stacktrace]

#0 vendor\\yageorgiy\\botman-vk-community-callback-driver\\src\\VkCommunityCallbackDriver.php(242): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', 'C:\\\\Data\\\\Dev\\\\lnu...', 242, Array)

#1 vendor\\botman\\botman\\src\\BotMan.php(192): BotMan\\Drivers\\VK\\VkCommunityCallbackDriver->getMessages()

#2 vendor\\botman\\botman\\src\\Traits\\HandlesConversations.php(170): BotMan\\BotMan\\BotMan->getMessages()

#3 vendor\\botman\\botman\\src\\BotMan.php(422): BotMan\\BotMan\\BotMan->loadActiveConversation()

#4 app\\Http\\Controllers\\BotManController.php(18): BotMan\\BotMan\\BotMan->listen()```

**Comment by yageorgiy** [comment]
Fixed in v.1.6.2.

**Comment by zakulqi** [comment]
> Fixed in v.1.6.2.

❤
