### ISSUE TITLE
"types" method api error, when sending message with attachment

### ISSUE THREAD

**Issue by zakulqi** [yageorgiy/botman-vk-community-callback-driver#6]
Code:
```
$attachment = new File('http://url');
$message = OutgoingMessage::create($text, $attachment);
$botman->say($message, $vkId);
```

Error:
```
    [content:protected] => {\"error\":{\"error_code\":100,\"error_msg\":\"One of the parameters specified was missing or invalid: you should specify correct user_id, chat_id, or domain param\",\"request_params\":[{\"key\":\"method\",\"value\":\"messages.setActivity\"},{\"key\":\"oauth\",\"value\":\"1\"},{\"key\":\"peer_id\",\"value\":\"\"},{\"key\":\"type\",\"value\":\"typing\"},{\"key\":\"v\",\"value\":\"5.103\"}]}}
    [version:protected] => 1.0
    [statusCode:protected] => 200
    [statusText:protected] => OK
    [charset:protected] => 
)
 at vendor\\yageorgiy\\botman-vk-community-callback-driver\\src\\VkCommunityCallbackDriver.php:1117)
[stacktrace]
#0 vendor\\yageorgiy\\botman-vk-community-callback-driver\\src\\VkCommunityCallbackDriver.php(1053): BotMan\\Drivers\\VK\\VkCommunityCallbackDriver->api('messages.setAct...', Array, true)
#1 vendor\\yageorgiy\\botman-vk-community-callback-driver\\src\\VkCommunityCallbackDriver.php(980): BotMan\\Drivers\\VK\\VkCommunityCallbackDriver->types(Object(BotMan\\BotMan\\Messages\\Incoming\\IncomingMessage))
#2 vendor\\yageorgiy\\botman-vk-community-callback-driver\\src\\VkCommunityCallbackDriver.php(850): BotMan\\Drivers\\VK\\VkCommunityCallbackDriver->prepareAttachments(Object(BotMan\\BotMan\\Messages\\Incoming\\IncomingMessage), Object(BotMan\\BotMan\\Messages\\Attachments\\File))
#3 vendor\\botman\\botman\\src\\BotMan.php(642): BotMan\\Drivers\\VK\\VkCommunityCallbackDriver->buildServicePayload(Object(BotMan\\BotMan\\Messages\\Outgoing\\OutgoingMessage), Object(BotMan\\BotMan\\Messages\\Incoming\\IncomingMessage), Array)
#4 vendor\\botman\\botman\\src\\BotMan.php(560): BotMan\\BotMan\\BotMan->reply(Object(BotMan\\BotMan\\Messages\\Outgoing\\OutgoingMessage), Array)
```

Debug:
```
public function types(IncomingMessage $matchingMessage)
    {
        dd($matchingMessage);
        $this->api("messages.setActivity", [
            "peer_id" => $matchingMessage->getRecipient(),
            "type" => "typing"
        ], true);

        return true;
    }
```
Debug output:
```
BotMan\BotMan\Messages\Incoming\IncomingMessage {#1901
  #message: ""
  #sender: 412312311
  #recipient: ""
  #images: []
  #videos: []
  #payload: null
```

My solution: 
```
public function types(IncomingMessage $matchingMessage)
    {
        $this->api("messages.setActivity", [
            "peer_id" => !empty($matchingMessage->getRecipient()) ? $matchingMessage->getRecipient() : $matchingMessage->getSender(),
            "type" => "typing"
        ], true);

        return true;
    }
```

AND The same error when uploading file. Code trying to call getRecipient:
```
private function prepareAttachments($matchingMessage, $attachment){
        $ret = [];
        $peer_id = $matchingMessage->getRecipient();
```

Must be replaced to:
```
$peer_id = !empty($matchingMessage->getRecipient()) ? $matchingMessage->getRecipient() : $matchingMessage->getSender();
```

**Comment by yageorgiy** [comment]
Fixed in v.1.6.3

**Comment by zakulqi** [comment]
❤
